workflows:
  build-ios:
    name: Build iOS IPA for Boa Terra App
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: CocoaPods install
        script: |
          cd ios
          pod install

      - name: Build IPA com Flutter sem assinatura
        script: flutter build ipa --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - boaterra.app@gmail.com
        notify:
          success: true
          failure: true
