workflows:
  build-ios:
    name: Build iOS IPA for Boa Terra App
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      flutter: stable
      xcode: latest
      vars:
        APPLE_TEAM_ID: SEU_TEAM_ID_AQUI

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: CocoaPods install
        script: |
          cd ios
          pod install

      - name: Gerar Runner.xcarchive com Team ID
        script: |
          mkdir -p build/ios/archive
          xcodebuild archive \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM=$APPLE_TEAM_ID

      - name: Exportar IPA com Team ID
        script: |
          mkdir -p build/ios/ipa
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/ios/ipa \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM=$APPLE_TEAM_ID

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - boaterra.app@gmail.com
        notify:
          success: true
          failure: true
