name: boa_terra_app
description: "App oficial da igreja – Cadastro de membros, líderes e igrejas"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_multi_formatter: ^2.7.0
  image: ^4.1.3


  # Firebase (core + auth + firestore) – compatíveis entre si
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # Firebase (armazenamento – se usar no futuro)
  firebase_storage: ^12.4.8

  # Gerenciamento de estado
  provider: ^6.1.1

  # Widgets e UI
  flutter_time_picker_spinner: ^2.0.0
  flutter_cupertino_datetime_picker: ^3.0.0
  google_fonts: ^6.2.0
  cupertino_icons: ^1.0.8

  # Recursos do dispositivo
  image_picker: ^1.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoBoaTerra.png"