// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJt_1fnz8sEXXcDNWQiOSslSbhxlET3sA',
    appId: '1:874343631841:web:3af4e7519b4e72d42b60a0',
    messagingSenderId: '874343631841',
    projectId: 'boa-terra-app',
    authDomain: 'boa-terra-app.firebaseapp.com',
    storageBucket: 'boa-terra-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2RKlxg5QPHdsZZ4MSZe_VtEtwhd8qpxk',
    appId: '1:874343631841:android:630c30df4e6e7c512b60a0',
    messagingSenderId: '874343631841',
    projectId: 'boa-terra-app',
    storageBucket: 'boa-terra-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRnLZ5qBIJUwvbugmS1iMDocIt9RVvz44',
    appId: '1:874343631841:ios:a392c4c2330ad5b82b60a0',
    messagingSenderId: '874343631841',
    projectId: 'boa-terra-app',
    storageBucket: 'boa-terra-app.appspot.com',
    iosBundleId: 'com.example.boaTerraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRnLZ5qBIJUwvbugmS1iMDocIt9RVvz44',
    appId: '1:874343631841:ios:a392c4c2330ad5b82b60a0',
    messagingSenderId: '874343631841',
    projectId: 'boa-terra-app',
    storageBucket: 'boa-terra-app.appspot.com',
    iosBundleId: 'com.example.boaTerraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJt_1fnz8sEXXcDNWQiOSslSbhxlET3sA',
    appId: '1:874343631841:web:7dc296ca597635032b60a0',
    messagingSenderId: '874343631841',
    projectId: 'boa-terra-app',
    authDomain: 'boa-terra-app.firebaseapp.com',
    storageBucket: 'boa-terra-app.appspot.com',
  );
}
